trigger:
- main

pool:
  name: 'Default' # Change this to your self-hosted agent pool name

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x' # Specify the version of Node.js you want to use
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build React app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'
